const PURCHASE_ROUTES = {
  START: '/start',
  ADDITIONAL: '/additional',
  SUMMARY: '/summary',
  LOGIN_SIGNUP: '/login-signup',
  CONTACT: '/contact',
  PAYMENT: '/payment',
  CONFIRMATION: '/confirmation',
}

const ADULT_BASE_PRICE = 65
const KID_BASE_PRICE = 45
const FAMILY_PROMOTION_MULTIPLIER = 0.8

const BURGER_RESTAURANT = 30
const BURGER_PLANETARIUM = 20
const BURGER_MUSICAL = 20

export {
  PURCHASE_ROUTES,
  ADULT_BASE_PRICE,
  KID_BASE_PRICE,
  FAMILY_PROMOTION_MULTIPLIER,
  BURGER_RESTAURANT,
  BURGER_PLANETARIUM,
  BURGER_MUSICAL,
}
